baseURL = 'https://satriafii.my.id'
languageCode = 'en-us'
title = 'Satriafii'
enableEmoji = true

[imaging]

quality = 55

[menus]
	[[menus.main]]
		name = 'ğŸ¡ Home'
		pageRef = '/'
		weight = 1
	[[menus.main]]
		name = 'ğŸ“– Posts'
		pageRef = '/post'
		weight = 2
	[[menus.main]]
		name = 'ğŸ“š Consumptions'
		pageRef = '/consumptions'
		weight = 3
	[[menus.main]]
		name = 'ğŸ–Œï¸ Creations'
		pageRef = '/creations'
		weight = 4
	[[menus.main]]
		name = 'ğŸ“¸ Photos'
		pageRef = '/photos'
		weight = 5
	[[menus.main]]
		name = 'ğŸ’­ Thoughts'
		pageRef = '/thoughts'
		weight = 6